name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: honyua/jupyterlab:laster
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  test:
    needs: build
    runs-on: ubuntu-latest
    #container: 
    #  image: honyua/jupyterlab:laster
    #  credentials:
    #    username: ${{ secrets.DOCKER_USERNAME }}
    #    password: ${{ secrets.DOCKER_PASSWORD }}
    #  ports:
    #    - 8080:8888
    #  volumes:
    #    - /root/jupyter:/root
    #    - /var/run/docker.sock:/var/run/docker.sock
    #     - /usr/bin/docker:/usr/bin/docker
    #  options: privileged
    steps:
      - name: docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} |docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: docker_run_jupyter
        run: docker run -d  
              --name jupyter 
              --privileged 
              -p 8888:8888 
              -v /root/jupyter:/root 
              -v /var/run/docker.sock:/var/run/docker.sock 
              -v /usr/bin/docker:/usr/bin/docker 
              honyua/jupyterlab:laster
      - name: sleep 3
        run: sleep 3
      - name: show log
        run: docker logs --since="2021-12-01" --tail=30 jupyter
      - name: show host ip
        run: ifconfig
        
